users:
  - count:
      tag: "一号账号"
      name: "张三"
      request_method: "get"
      url: "https://dounai.lol/user/checkin"
      bark_token: "xxxxxx"
      head:
        user-agent: "Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Mobile Safari/537.36"
        cookie: "cookie here"
  - count:
      tag: "二号账号"
      name: "李四"
      request_method: "get"
      url: "https://dounai.lol/user/checkin"
      bark_token: "xxxxxx"
      head:
        user-agent: "Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Mobile Safari/537.36"
        cookie: "cookie here"
